# syntax=docker/dockerfile:1.4
FROM node:20-alpine3.18

WORKDIR /app

# Skip npm upgrade since the alpine image comes with compatible versions
COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm install

COPY . .

CMD ["npm", "run", "dev"]